apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::484907523966:user/Terraform-EKS
      username: Terraform-EKS
      groups:
        - system:masters
